### PR TITLE
proposal for an Ensamble estimator 

### PR DESCRIPTION
**Pull request by paolof89**
proposal for an Ensamble estimator with different models and different input sets

### CODE REVIEW

**Comment by pasquierjb** [comment]
Hi Paolo! Thanks for the nice work! 
Quick question on your code. Why did you decide to do the following:
```      
 if self.meta_regressor is None:  
    self.meta_regressor = SVR(kernel='rbf')
```
Wouldn't it more intuitive to have a default meta_regressor that just averages the predictions?
```
class MeanRegressor(BaseEstimator):
    def fit(self, X, y=None):
        return self

    def predict(self, X, y=None):
        return(np.mean(X, axis=1))
```

**Comment by paolof89** [comment]
Hi Pasquierjb,
You are right, the default should be the MeanRegressor.

**Comment by pasquierjb** [comment]
Is it possible to use sklearn cross_val_score with  this class and pass it the column_selection argument in some way?

**Comment by paolof89** [comment]
Yes, in principle should be possible using the argument fit_params.
`from sklearn.model_selection import cross_val_score
cross_val_score(estimator=mymodel, X=df, y=df['target'], fit_params={'column_selection': [input_model1, input_model2]})
`
The problem is that the cross_val_score function makes a copy of the estimator with the clone function of sklearn. This function doesn't copy the internal attributes of the estimator, I'll check if there is an issue or if I need to add some method to the custom estimator.
At the moment I added the __copy__ method but it doesn't help.
`    def __copy__(self):
        return MyEnsembleRegressor(self.my_esitimators, self.meta_regressor)`

**Comment by paolof89** [comment]
I have the solution.
I made a terrible mistake in the __init__ method:
`self.my_esitimators = regressors`
must be changed in:
`self.regressors= regressors`
It's a best practice to not change the name between the input parameters and the internal attributes.
Now I know why: the method get_params (of BaseEstimator) will not return that parameters .

If you do this refactor then the cross_val_score function will work

**Comment by lorenzori** [comment]
thanks @paolof89 ! @pasquierjb whos editing that?

**Pull request merged**
